---
- name: OS 기본 환경 및 보안 설정 최적화
  ansible.builtin.import_tasks: 01_os_base.yml

- name: 커널 모듈 및 네트워크 커널 파라미터(sysctl) 설정
  ansible.builtin.import_tasks: 02_kernel_sysctl.yml

- name: 컨테이너 런타임(containerd) 및 Cgroup V2 연동
  ansible.builtin.import_tasks: 03_containerd.yml

- name: 쿠버네티스 컴포넌트(kubeadm, kubelet, kubectl) 설치
  ansible.builtin.import_tasks: 04_kubernetes.yml