---
- name: 쿠버네티스 마스터 노드 초기화 (Calico CIDR 반영)
  
  ansible.builtin.command: "kubeadm init --pod-network-cidr={{ k8s_pod_network_cidr }}"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: init_output
  changed_when: true
  args:
    creates: /etc/kubernetes/admin.conf

- name: 일반 사용자를 위한 kubeconfig 폴더 생성
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: admin.conf 설정 파일을 사용자 폴더로 복사 및 권한 부여
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: yes
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: 조인 정보 메타데이터 저장
  ansible.builtin.shell: |
    TOKEN=$(kubeadm token create --ttl 0)
    HASH=$(openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //')
    
    # GCP 프로젝트 메타데이터에 저장
    gcloud compute project-info add-metadata --metadata=k8s-join-token=$TOKEN,k8s-ca-hash=$HASH
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: KSM 원격 배포를 위한 git 설치
  ansible.builtin.dnf:
    name: git
    state: present

- name: Kube-State-Metrics (KSM) 표준 매니페스트 배포
  ansible.builtin.command: "kubectl apply -k https://github.com/kubernetes/kube-state-metrics/examples/standard"
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  register: ksm_deploy
  changed_when: "'created' in ksm_deploy.stdout or 'configured' in ksm_deploy.stdout"

- name: 쿠버네티스 메트릭 서버(Metrics Server) 매니페스트 다운로드
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    dest: /tmp/metrics-server.yaml
    mode: '0644'

- name: 사설 클러스터 통신을 위한 TLS 인증서 검증 무시 옵션 주입
  ansible.builtin.replace:
    path: /tmp/metrics-server.yaml
    regexp: '^(\s*)-\s*--secure-port=(\d+)\s*$'
    replace: '\1- --secure-port=\2\n\1- --kubelet-insecure-tls'

- name: 메트릭 서버 클러스터에 배포
  kubernetes.core.k8s:
    state: present
    src: /tmp/metrics-server.yaml
    kubeconfig: /etc/kubernetes/admin.conf